# Generated by Django 4.1.5 on 2023-02-02 08:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='токен'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
