# Generated by Django 4.1.5 on 2023-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(default='', editable=False, max_length=250, verbose_name='slug')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='изображение')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('publicate', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('count', models.BigIntegerField(default=0, verbose_name='количество просмотров')),
            ],
        ),
    ]
