# Generated by Django 4.1.5 on 2023-01-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publicate',
            field=models.BooleanField(choices=[('active', 'Опубликованный'), ('inactive', 'Не опубликованный')],
                                      default='active', max_length=10),
        ),
    ]
