# Generated by Django 4.1.5 on 2023-02-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_user_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('set_published_status', 'Can publish article')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_title_product', 'Can title product'), ('set_category_product', 'Can category product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='publicate',
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.CharField(choices=[('active', 'Опубликованный'), ('inactive', 'Не опубликованный')], default='inactive', max_length=10),
        ),
    ]
