# Generated by Django 4.1.5 on 2023-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_alter_article_publicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publicate',
            field=models.CharField(choices=[('active', 'Опубликованный'), ('inactive', 'Не опубликованный')],
                                   default='active', max_length=10),
        ),
    ]
